apiVersion: v1
kind: Pod
metadata:
  name: soma-api
  labels:
    app: soma-api
spec:
  containers:
    - name: soma-api
      image: soma-api
      ports:
        - containerPort: 8000
      imagePullPolicy: Never